# Generated by Django 4.1.3 on 2022-12-01 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingradient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingradient',
            new_name='Ingredient',
        ),
    ]
